# Generated by Django 3.2.6 on 2021-09-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magnifico_ranks', '0004_auto_20210920_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='review',
        ),
        migrations.AddField(
            model_name='project',
            name='ratings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riet', to='magnifico_ranks.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magnifico_ranks.project'),
        ),
    ]
