# Generated by Django 3.2.6 on 2021-09-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magnifico_ranks', '0005_auto_20210920_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riet', to='magnifico_ranks.review'),
        ),
    ]
