# Generated by Django 3.2.6 on 2021-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnifico_ranks', '0006_alter_project_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='content_avg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='design_avg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='usability_avg',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
