# Generated by Django 3.2.6 on 2021-09-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnifico_ranks', '0007_auto_20210922_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
    ]
