# Generated by Django 3.2.6 on 2021-09-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magnifico_ranks', '0008_remove_review_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magnifico_ranks.project'),
        ),
    ]
